name = "ParMETIS"
uuid = "cbb674b7-49ff-4c21-8a97-68bdd8bf5d23"
authors = ["Alexis Montoison"]
version = "0.1.0"

[deps]
PARMETIS_jll = "b247a4be-ddc1-5759-8008-7e02fe3dbdaa"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
